[workspace]
members = [
    "crates/cli",
    "crates/core",
    "crates/daemon",
    "crates/platform",
    "crates/proto",
]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.98"
publish = false

[workspace.dependencies]
prost = "=0.14.4"
prost-build = "=0.14.4"
protoc-bin-vendored = "=3.2.0"
zterm-core = { path = "crates/core" }
zterm-daemon = { path = "crates/daemon" }
zterm-platform = { path = "crates/platform" }
zterm-proto = { path = "crates/proto" }

[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
