const bashIntegrationScript = [
  "if [ -n \"${ZTERM_SHELL_INTEGRATION:-}\" ]; then",
  '  builtin return',
  'fi',
  '',
  'ZTERM_SHELL_INTEGRATION=1',
  '',
  'if [ -r ~/.bashrc ]; then',
  '  . ~/.bashrc',
  'fi',
  '',
  '__zterm_escape_value() {',
  '  builtin local out',
  '  out=${1//\\/\\\\}',
  '  out=${out//;/\\x3b}',
  "  builtin printf '%s\\n' \"$out\"",
  '}',
  '',
  '__zterm_update_cwd() {',
  "  builtin printf '\\e]633;P;Cwd=%s\\a' \"$(__zterm_escape_value \"${PWD}\")\"",
  '}',
  '',
  'PROMPT_COMMAND="__zterm_update_cwd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"',
  '__zterm_update_cwd'
].join('\n')

const zshIntegrationScript = [
  'builtin autoload -Uz add-zsh-hook 2>/dev/null',
  '',
  'if [ -n "$ZTERM_SHELL_INTEGRATION" ]; then',
  '  ZDOTDIR=$USER_ZDOTDIR',
  '  builtin return',
  'fi',
  '',
  'ZTERM_SHELL_INTEGRATION=1',
  '',
  'if [[ "$USER_ZDOTDIR" != "$ZDOTDIR" ]] && [[ -f "$USER_ZDOTDIR/.zshrc" ]]; then',
  '  . "$USER_ZDOTDIR/.zshrc"',
  'fi',
  '',
  'if [[ "$USER_ZDOTDIR" != "$ZDOTDIR" ]]; then',
  '  HISTFILE=$USER_ZDOTDIR/.zsh_history',
  'fi',
  '',
  '__zterm_escape_value() {',
  '  builtin emulate -L zsh',
  '  builtin local out="$1"',
  '  out=${out//\\/\\\\}',
  '  out=${out//;/\\x3b}',
  '  builtin print -r -- "$out"',
  '}',
  '',
  '__zterm_update_cwd() {',
  "  builtin printf '\\e]633;P;Cwd=%s\\a' \"$(__zterm_escape_value \"${PWD}\")\"",
  '}',
  '',
  'add-zsh-hook chpwd __zterm_update_cwd 2>/dev/null',
  'precmd_functions=(__zterm_update_cwd $precmd_functions)',
  '__zterm_update_cwd'
].join('\n')

export function createSshShellLaunchCommand(): string {
  return [
    'zterm_shell_path="${SHELL:-}"',
    'zterm_shell_name="${zterm_shell_path##*/}"',
    'zterm_tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/zterm-shell.XXXXXX" 2>/dev/null || mktemp -d -t zterm-shell)"',
    'if [ -z "$zterm_tmpdir" ] || [ ! -d "$zterm_tmpdir" ]; then',
    '  export TERM_PROGRAM="zterm"',
    '  exec "${zterm_shell_path:-/bin/sh}" -i',
    'fi',
    'chmod 700 "$zterm_tmpdir" 2>/dev/null || true',
    'case "$zterm_shell_name" in',
    '  bash)',
    '    cat <<\'__ZTERM_BASH_INTEGRATION__\' > "$zterm_tmpdir/.zterm-bashrc"',
    bashIntegrationScript,
    '__ZTERM_BASH_INTEGRATION__',
    '    export TERM_PROGRAM="zterm"',
    '    exec "${zterm_shell_path:-bash}" --init-file "$zterm_tmpdir/.zterm-bashrc" -i',
    '    ;;',
    '  zsh)',
    '    export TERM_PROGRAM="zterm"',
    '    export USER_ZDOTDIR="${ZDOTDIR:-$HOME}"',
    '    mkdir -p "$zterm_tmpdir/zsh"',
    '    cat <<\'__ZTERM_ZSH_INTEGRATION__\' > "$zterm_tmpdir/zsh/.zshrc"',
    zshIntegrationScript,
    '__ZTERM_ZSH_INTEGRATION__',
    '    ZDOTDIR="$zterm_tmpdir/zsh" exec "${zterm_shell_path:-zsh}" -i',
    '    ;;',
    '  *)',
    '    export TERM_PROGRAM="zterm"',
    '    exec "${zterm_shell_path:-/bin/sh}" -i',
    '    ;;',
    'esac'
  ].join('\n')
}
