[package]
name = "zterm-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
iroh.workspace = true
futures-util.workspace = true
ring.workspace = true
prost.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zeroize.workspace = true
zterm-proto.workspace = true
zterm-core.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
