[package]
name = "zterm-release-tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
flate2.workspace = true
ring.workspace = true
semver.workspace = true
serde_json.workspace = true
tar.workspace = true
zeroize.workspace = true
zterm-core.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
