export const IPC_CHANNELS = {
  TERMINAL_CREATE: 'terminal:create',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_KILL: 'terminal:kill',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',
  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_GET_ALL: 'store:getAll',
  CLIPBOARD_READ_TEXT: 'clipboard:readText',
  CLIPBOARD_WRITE_TEXT: 'clipboard:writeText',
  CONNECTIONS_LIST: 'connections:list',
  CONNECTIONS_SAVE: 'connections:save',
  CONNECTIONS_DELETE: 'connections:delete',
  SFTP_GET_INITIAL_DIRECTORY: 'sftp:getInitialDirectory',
  SFTP_LIST_DIRECTORY: 'sftp:listDirectory',
  SFTP_UPLOAD_FILE: 'sftp:uploadFile',
  SFTP_DOWNLOAD_ENTRY: 'sftp:downloadEntry',
  SFTP_GET_ENTRY_DETAILS: 'sftp:getEntryDetails'
} as const
