//! Transport admission limits and connection duplicate arbitration.

use std::time::Duration;

use crate::{
    AuthGeneration, Capabilities, ConnectionAttemptId, DeviceDisplayName, DeviceDisplayNameError,
    DeviceId, IdLengthError,
};

/// Deterministic identity of one connection dial attempt.
///
/// Both endpoints derive the same key from the Iroh-authenticated initiator
/// identity and the attempt ID generated by the dialer, then select the
/// lexicographic minimum as the designated primary connection. The wire never
/// carries the initiator identity; each side verifies it from the Iroh
/// connection side.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ConnectionCandidateKey {
    /// Authenticated initiator device identity.
    pub initiator: DeviceId,
    /// Random attempt ID generated by the dialer.
    pub attempt: ConnectionAttemptId,
}

impl ConnectionCandidateKey {
    /// Constructs a candidate key from its two components.
    #[must_use]
    pub const fn new(initiator: DeviceId, attempt: ConnectionAttemptId) -> Self {
        Self { initiator, attempt }
    }
}

/// Deterministically selects the designated primary candidate.
///
/// Candidate keys sort lexicographically over `(initiator bytes, attempt
/// bytes)`, so every observer converges on the same winner regardless of
/// registration order.
#[must_use]
pub fn designated_primary(
    keys: impl IntoIterator<Item = ConnectionCandidateKey>,
) -> Option<ConnectionCandidateKey> {
    keys.into_iter().min()
}

/// Maximum encoded pairing ticket text bytes before base64 decoding.
pub const MAX_TICKET_TEXT_BYTES: usize = 16 * 1024;
/// Maximum relay hints in one ticket or relay route cache.
pub const MAX_RELAY_HINTS: usize = 4;
/// Maximum hello or pair frame body bytes.
pub const MAX_PAIR_HELLO_FRAME_BYTES: usize = 16 * 1024;
/// Maximum total bytes exchanged in one pairing handshake.
pub const MAX_PAIR_HANDSHAKE_BYTES: usize = 64 * 1024;

/// Foundation-approved transport admission and deadline policy.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TransportLimits {
    /// Maximum simultaneously authenticated remote connections.
    pub max_remote_connections: usize,
    /// Maximum pending outbound dials across all endpoints.
    pub max_pending_dials: usize,
    /// Maximum pending outbound dials for one endpoint.
    pub max_pending_dials_per_endpoint: usize,
    /// Maximum accepted-but-not-authenticated normal connections.
    pub max_unauthenticated_connections: usize,
    /// Maximum accepted-but-not-authenticated connections for one endpoint.
    pub max_unauthenticated_per_endpoint: usize,
    /// Maximum concurrent pairing handshakes.
    pub max_pairing_handshakes: usize,
    /// Maximum concurrent pairing handshakes for one endpoint.
    pub max_pairing_per_endpoint: usize,
    /// Maximum bidirectional streams per connection.
    pub max_bi_streams_per_connection: usize,
    /// Maximum concurrent stream handlers per connection.
    pub max_stream_handlers_per_connection: usize,
    /// Maximum concurrent stream handlers across all connections.
    pub max_stream_handlers_global: usize,
    /// Maximum open-stream request queue depth per connection.
    pub max_open_stream_queue_per_connection: usize,
    /// Maximum live pairing offers retained in memory.
    pub max_live_pair_offers: usize,
    /// Maximum encoded ticket text bytes.
    pub max_ticket_text_bytes: usize,
    /// Maximum relay hints in one ticket or route cache.
    pub max_relay_hints: usize,
    /// Maximum bytes in one relay hint URL.
    pub max_relay_url_bytes: usize,
    /// Maximum hello or pair frame body bytes.
    pub max_pair_hello_frame_bytes: usize,
    /// Maximum total bytes exchanged in one pairing handshake.
    pub max_pair_handshake_bytes: usize,
    /// Deadline for the first application frame on an accepted stream.
    pub first_frame_deadline: Duration,
    /// Deadline for one complete pairing handshake.
    pub pairing_total_deadline: Duration,
    /// Budget for one fresh signed address lookup.
    pub address_lookup_budget: Duration,
    /// Budget for one connect attempt.
    pub connect_attempt_budget: Duration,
}

impl Default for TransportLimits {
    fn default() -> Self {
        Self {
            max_remote_connections: 32,
            max_pending_dials: 16,
            max_pending_dials_per_endpoint: 1,
            max_unauthenticated_connections: 16,
            max_unauthenticated_per_endpoint: 2,
            max_pairing_handshakes: 8,
            max_pairing_per_endpoint: 1,
            max_bi_streams_per_connection: 32,
            max_stream_handlers_per_connection: 16,
            max_stream_handlers_global: 128,
            max_open_stream_queue_per_connection: 32,
            max_live_pair_offers: 16,
            max_ticket_text_bytes: MAX_TICKET_TEXT_BYTES,
            max_relay_hints: MAX_RELAY_HINTS,
            max_relay_url_bytes: 2048,
            max_pair_hello_frame_bytes: MAX_PAIR_HELLO_FRAME_BYTES,
            max_pair_handshake_bytes: MAX_PAIR_HANDSHAKE_BYTES,
            first_frame_deadline: Duration::from_secs(5),
            pairing_total_deadline: Duration::from_secs(15),
            address_lookup_budget: Duration::from_secs(2),
            connect_attempt_budget: Duration::from_secs(10),
        }
    }
}

impl TransportLimits {
    /// Rejects a configuration whose count or deadline is zero.
    ///
    /// Every admission and deadline bound must be non-zero so an exhausted or
    /// misconfigured transport fails closed with `resource_exhausted` instead of
    /// accepting unbounded work or a zero deadline.
    pub fn validate(&self) -> Result<(), TransportLimitsError> {
        let counts = [
            ("max_remote_connections", self.max_remote_connections),
            ("max_pending_dials", self.max_pending_dials),
            (
                "max_pending_dials_per_endpoint",
                self.max_pending_dials_per_endpoint,
            ),
            (
                "max_unauthenticated_connections",
                self.max_unauthenticated_connections,
            ),
            (
                "max_unauthenticated_per_endpoint",
                self.max_unauthenticated_per_endpoint,
            ),
            ("max_pairing_handshakes", self.max_pairing_handshakes),
            ("max_pairing_per_endpoint", self.max_pairing_per_endpoint),
            (
                "max_bi_streams_per_connection",
                self.max_bi_streams_per_connection,
            ),
            (
                "max_stream_handlers_per_connection",
                self.max_stream_handlers_per_connection,
            ),
            (
                "max_stream_handlers_global",
                self.max_stream_handlers_global,
            ),
            (
                "max_open_stream_queue_per_connection",
                self.max_open_stream_queue_per_connection,
            ),
            ("max_live_pair_offers", self.max_live_pair_offers),
            ("max_ticket_text_bytes", self.max_ticket_text_bytes),
            ("max_relay_hints", self.max_relay_hints),
            ("max_relay_url_bytes", self.max_relay_url_bytes),
            (
                "max_pair_hello_frame_bytes",
                self.max_pair_hello_frame_bytes,
            ),
            ("max_pair_handshake_bytes", self.max_pair_handshake_bytes),
        ];
        for (field, value) in counts {
            if value == 0 {
                return Err(TransportLimitsError::ZeroLimit { field });
            }
        }
        let deadlines = [
            ("first_frame_deadline", self.first_frame_deadline),
            ("pairing_total_deadline", self.pairing_total_deadline),
            ("address_lookup_budget", self.address_lookup_budget),
            ("connect_attempt_budget", self.connect_attempt_budget),
        ];
        for (field, value) in deadlines {
            if value.is_zero() {
                return Err(TransportLimitsError::ZeroLimit { field });
            }
        }
        Ok(())
    }
}

/// Failure while validating transport limits.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TransportLimitsError {
    /// A count or deadline resolved to zero.
    ZeroLimit {
        /// Name of the offending limit field.
        field: &'static str,
    },
}

impl std::fmt::Display for TransportLimitsError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ZeroLimit { field } => {
                write!(formatter, "transport limit {field} must be non-zero")
            }
        }
    }
}

impl std::error::Error for TransportLimitsError {}

/// Failure while validating a connection handshake message.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ConnectionError {
    /// The connection attempt ID had the wrong fixed byte width.
    InvalidAttemptId(IdLengthError),
    /// A display, build, or platform string failed its product bound.
    InvalidText(crate::PairTicketError),
    /// A peer display name failed the shared device-name contract.
    InvalidDisplay(DeviceDisplayNameError),
    /// An authorization generation exceeded the SQLite signed 64-bit ceiling.
    InvalidGeneration {
        /// Observed generation value.
        actual: u64,
    },
    /// The wire-major range is empty or inverted.
    InvalidWireRange {
        /// Minimum wire major.
        min: u32,
        /// Maximum wire major.
        max: u32,
    },
    /// A responder selected the reserved zero wire major.
    InvalidWireMajor {
        /// Observed selected major.
        actual: u32,
    },
    /// A normal authenticated welcome used the reserved zero generation.
    ZeroAuthorizationGeneration,
}

impl std::fmt::Display for ConnectionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidAttemptId(error) => error.fmt(formatter),
            Self::InvalidText(error) => error.fmt(formatter),
            Self::InvalidDisplay(error) => error.fmt(formatter),
            Self::InvalidGeneration { actual } => {
                write!(
                    formatter,
                    "authorization generation {actual} exceeds the signed 64-bit ceiling"
                )
            }
            Self::InvalidWireRange { min, max } => {
                write!(formatter, "invalid wire-major range {min}..={max}")
            }
            Self::InvalidWireMajor { actual } => {
                write!(formatter, "invalid selected wire major {actual}")
            }
            Self::ZeroAuthorizationGeneration => write!(
                formatter,
                "connection welcome requires a non-zero authorization generation"
            ),
        }
    }
}

impl std::error::Error for ConnectionError {}

/// Validated initiator half of the normal connection handshake.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConnectionHello {
    min_wire_major: u32,
    max_wire_major: u32,
    capabilities: Capabilities,
    attempt_id: ConnectionAttemptId,
    initiator_display: DeviceDisplayName,
    initiator_build: String,
    initiator_platform: String,
}

impl ConnectionHello {
    /// Validates the initiator half of the normal connection handshake.
    pub fn new(
        min_wire_major: u32,
        max_wire_major: u32,
        capabilities: Capabilities,
        attempt_id: ConnectionAttemptId,
        initiator_display: impl Into<String>,
        initiator_build: impl Into<String>,
        initiator_platform: impl Into<String>,
    ) -> Result<Self, ConnectionError> {
        if min_wire_major == 0 || min_wire_major > max_wire_major {
            return Err(ConnectionError::InvalidWireRange {
                min: min_wire_major,
                max: max_wire_major,
            });
        }
        let initiator_display =
            DeviceDisplayName::new(initiator_display).map_err(ConnectionError::InvalidDisplay)?;
        let initiator_build = initiator_build.into();
        let initiator_platform = initiator_platform.into();
        for text in [&initiator_build, &initiator_platform] {
            crate::pairing::validate_device_name(text).map_err(ConnectionError::InvalidText)?;
        }
        Ok(Self {
            min_wire_major,
            max_wire_major,
            capabilities,
            attempt_id,
            initiator_display,
            initiator_build,
            initiator_platform,
        })
    }

    /// Minimum accepted wire major.
    #[must_use]
    pub const fn min_wire_major(&self) -> u32 {
        self.min_wire_major
    }

    /// Maximum accepted wire major.
    #[must_use]
    pub const fn max_wire_major(&self) -> u32 {
        self.max_wire_major
    }

    /// Capability bits, unknown bits retained.
    #[must_use]
    pub const fn capabilities(&self) -> Capabilities {
        self.capabilities
    }

    /// Connection attempt identifier.
    #[must_use]
    pub const fn attempt_id(&self) -> ConnectionAttemptId {
        self.attempt_id
    }

    /// Initiator display name.
    #[must_use]
    pub fn initiator_display(&self) -> &str {
        self.initiator_display.as_str()
    }

    /// Initiator build version.
    #[must_use]
    pub fn initiator_build(&self) -> &str {
        &self.initiator_build
    }

    /// Initiator platform.
    #[must_use]
    pub fn initiator_platform(&self) -> &str {
        &self.initiator_platform
    }
}

/// Validated responder half of the normal connection handshake.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConnectionWelcome {
    wire_major: u32,
    capabilities: Capabilities,
    responder_display: DeviceDisplayName,
    responder_build: String,
    responder_platform: String,
    accepted_authorization_generation: AuthGeneration,
}

impl ConnectionWelcome {
    /// Validates the responder half of the normal connection handshake.
    pub fn new(
        wire_major: u32,
        capabilities: Capabilities,
        responder_display: impl Into<String>,
        responder_build: impl Into<String>,
        responder_platform: impl Into<String>,
        accepted_authorization_generation: AuthGeneration,
    ) -> Result<Self, ConnectionError> {
        if wire_major == 0 {
            return Err(ConnectionError::InvalidWireMajor { actual: wire_major });
        }
        if accepted_authorization_generation == AuthGeneration::ZERO {
            return Err(ConnectionError::ZeroAuthorizationGeneration);
        }
        let responder_display =
            DeviceDisplayName::new(responder_display).map_err(ConnectionError::InvalidDisplay)?;
        let responder_build = responder_build.into();
        let responder_platform = responder_platform.into();
        for text in [&responder_build, &responder_platform] {
            crate::pairing::validate_device_name(text).map_err(ConnectionError::InvalidText)?;
        }
        Ok(Self {
            wire_major,
            capabilities,
            responder_display,
            responder_build,
            responder_platform,
            accepted_authorization_generation,
        })
    }

    /// Selected wire major.
    #[must_use]
    pub const fn wire_major(&self) -> u32 {
        self.wire_major
    }

    /// Capability bits, unknown bits retained.
    #[must_use]
    pub const fn capabilities(&self) -> Capabilities {
        self.capabilities
    }

    /// Responder display name.
    #[must_use]
    pub fn responder_display(&self) -> &str {
        self.responder_display.as_str()
    }

    /// Responder build version.
    #[must_use]
    pub fn responder_build(&self) -> &str {
        &self.responder_build
    }

    /// Responder platform.
    #[must_use]
    pub fn responder_platform(&self) -> &str {
        &self.responder_platform
    }

    /// Receiver-side accepted authorization generation.
    #[must_use]
    pub const fn accepted_authorization_generation(&self) -> AuthGeneration {
        self.accepted_authorization_generation
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn candidate_order_is_deterministic_regardless_of_registration() {
        let initiator = DeviceId::from_array([0x01; 32]);
        let attempt_a = ConnectionAttemptId::from_array([0x02; 16]);
        let attempt_b = ConnectionAttemptId::from_array([0x03; 16]);
        let first = ConnectionCandidateKey::new(initiator, attempt_a);
        let second = ConnectionCandidateKey::new(initiator, attempt_b);
        assert_eq!(designated_primary([first, second]), Some(first));
        assert_eq!(designated_primary([second, first]), Some(first));

        // A lexicographically smaller initiator always wins over a larger one.
        let small_initiator = DeviceId::from_array([0x00; 32]);
        let large = ConnectionCandidateKey::new(initiator, attempt_a);
        let small = ConnectionCandidateKey::new(small_initiator, attempt_b);
        assert_eq!(designated_primary([large, small]), Some(small));

        // Deterministic xorshift corpus with long equal prefixes exercises the
        // complete bytewise ordering without adding a production RNG owner.
        let mut state = 0x9e37_79b9_7f4a_7c15_u64;
        let mut corpus = Vec::new();
        for index in 0..128_u8 {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            let mut initiator_bytes = [0x55; 32];
            initiator_bytes[24..].copy_from_slice(&state.to_be_bytes());
            let mut attempt_bytes = [0xaa; 16];
            attempt_bytes[15] = index;
            corpus.push(ConnectionCandidateKey::new(
                DeviceId::from_array(initiator_bytes),
                ConnectionAttemptId::from_array(attempt_bytes),
            ));
        }
        let expected = *corpus.iter().min().expect("non-empty corpus");
        assert_eq!(designated_primary(corpus.iter().copied()), Some(expected));
        corpus.reverse();
        assert_eq!(designated_primary(corpus), Some(expected));
    }

    #[test]
    fn default_limits_match_the_foundation_policy_and_reject_zero() {
        let limits = TransportLimits::default();
        assert_eq!(limits.max_remote_connections, 32);
        assert_eq!(limits.max_pending_dials, 16);
        assert_eq!(limits.max_pending_dials_per_endpoint, 1);
        assert_eq!(limits.max_bi_streams_per_connection, 32);
        assert_eq!(limits.max_ticket_text_bytes, 16 * 1024);
        assert_eq!(limits.max_relay_hints, 4);
        assert_eq!(limits.max_relay_url_bytes, 2048);
        assert_eq!(limits.max_pair_handshake_bytes, 64 * 1024);
        assert_eq!(limits.first_frame_deadline, Duration::from_secs(5));
        limits.validate().expect("defaults are non-zero");

        let zero = TransportLimits {
            max_remote_connections: 0,
            ..TransportLimits::default()
        };
        assert!(matches!(
            zero.validate(),
            Err(TransportLimitsError::ZeroLimit {
                field: "max_remote_connections"
            })
        ));
    }
}
